In [2]:
import os
import pandas as pd

In [6]:
df_train = pd.read_csv("../data/collaborative_filtering/train.csv")
df_train

         user    item  rating
0           1   25715     7.0
1           1   25716    10.0
2           5   25851     9.0
3           6   25923     5.0
4           7   25924     6.0
...       ...     ...     ...
390346  77801  185970     5.0
390347  77801  185971     5.0
390348  77802   44671    10.0
390349  77803  154450    10.0
390350  77804  185972     8.0

[390351 rows x 3 columns]

In [14]:
def filtrar_por_minimos(df, min_item=3, min_user=3, iterativo=True):
    """
    Filtra un dataframe de interacciones (user, item, rating) eliminando:
    - usuarios con menos de min_user valoraciones
    - ítems con menos de min_item valoraciones

    Parámetros
    ----------
    df : pd.DataFrame
        Debe contener columnas 'user' e 'item' (y opcionalmente 'rating').
    min_item : int
        Mínimo de valoraciones por ítem.
    min_user : int
        Mínimo de valoraciones por usuario.
    iterativo : bool
        Si True, repite el filtrado hasta que no haya más cambios.

    Retorna
    -------
    pd.DataFrame
        DataFrame filtrado.
    """
    out = df.copy()

    if not iterativo:
        usuarios_validos = out["user"].value_counts()
        usuarios_validos = usuarios_validos[usuarios_validos >= min_user].index
        out = out[out["user"].isin(usuarios_validos)]

        items_validos = out["item"].value_counts()
        items_validos = items_validos[items_validos >= min_item].index
        out = out[out["item"].isin(items_validos)]

        return out.reset_index(drop=True)

    # Filtrado iterativo (recomendado)
    while True:
        n_antes = len(out)

        usuarios_validos = out["user"].value_counts()
        usuarios_validos = usuarios_validos[usuarios_validos >= min_user].index
        out = out[out["user"].isin(usuarios_validos)]

        items_validos = out["item"].value_counts()
        items_validos = items_validos[items_validos >= min_item].index
        out = out[out["item"].isin(items_validos)]

        if len(out) == n_antes:
            break

    return out.reset_index(drop=True)

# Ejemplo de uso:
df_train_filtrado = filtrar_por_minimos(df_train, min_item=0, min_user=2)
df_train_filtrado

         user    item  rating
0           1   25715     7.0
1           1   25716    10.0
2           7   25924     6.0
3           7   25925     7.0
4           7   25926     7.0
...       ...     ...     ...
347317  77801   16877     9.0
347318  77801   26782     6.0
347319  77801   28098     7.0
347320  77801  185970     5.0
347321  77801  185971     5.0

[347322 rows x 3 columns]

In [15]:
df_train_filtrado.to_csv("../data/cut_1_0/train.csv", index=False)